################################################################################
#                      OT-2: Man-Ray and The Dirty Bubble                      #
#                   ----------------------------------------                   #
#                         Gas Generator Sizing Results                         #
#                                                                              #
#                             Generated at: XX:27                              #
#                                                                              #
################################################################################


################################################################################
#---------------------------------- Geometry ----------------------------------#
################################################################################

gas_generator:

  geometry:

    injector:

      fuel:
        cda: 1.4888141968529582e-06
        name: IPA
        stiffness: 0.9999932250331157


      oxidiser:
        cda: 7.864754350188712e-07
        name: NitrousOxide
        stiffness: 0.9999932249891962


    chamber:
      a_e: 0.00024381129113510775
      a_t: 6.145284669949664e-05


################################################################################
#------------------------------ Operating Point -------------------------------#
################################################################################

  operating_point:

    MR: 0.500

    m_dot:
      fuel: 0.09333317525010332
      oxidiser: 0.04666669243376167
      total: 0.14000046129125576


    gas:
      P: 2500008.468737293
      R: 537.4735344209124
      T: 970.1654223020483
      cp: 2688.8464654626055
      gamma: 1.2498281570181644


